apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  consumer-ingress
  namespace: leaf-image-management-system
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /image-plant/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: consumer
                port:
                  number: 80
